version: '3'
services:
  # Service pour la base de données MySQL
  db:
    image: mysql:5.7
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toorpwd
      MYSQL_DATABASE: database_development
      MYSQL_USER: rooter
      MYSQL_PASSWORD: toor
    ports:
      - "3306:3306"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8801:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: toorpwd
  # Service pour le backend Node.js
  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: rooter
      DB_PASSWORD: toor
      DB_NAME: database_development

  # Service pour le frontend
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - backend